/*
 * Infoplus API
 * Infoplus API.
 *
 * OpenAPI spec version: beta
 * Contact: api@infopluscommerce.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.infopluscommerce.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.threeten.bp.OffsetDateTime;

/**
 * DasFees
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2026-02-27T09:14:08.249-06:00")
public class DasFees {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("createDate")
  private OffsetDateTime createDate = null;

  @SerializedName("modifyDate")
  private OffsetDateTime modifyDate = null;

  @SerializedName("carrierCompanyCode")
  private String carrierCompanyCode = null;

  @SerializedName("zip")
  private String zip = null;

  @SerializedName("dasFeeType")
  private String dasFeeType = null;

  @SerializedName("fee")
  private BigDecimal fee = null;

  @SerializedName("customFields")
  private Map<String, Object> customFields = null;

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Integer getId() {
    return id;
  }

   /**
   * Get createDate
   * @return createDate
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getCreateDate() {
    return createDate;
  }

   /**
   * Get modifyDate
   * @return modifyDate
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getModifyDate() {
    return modifyDate;
  }

  public DasFees carrierCompanyCode(String carrierCompanyCode) {
    this.carrierCompanyCode = carrierCompanyCode;
    return this;
  }

   /**
   * Get carrierCompanyCode
   * @return carrierCompanyCode
  **/
  @ApiModelProperty(required = true, value = "")
  public String getCarrierCompanyCode() {
    return carrierCompanyCode;
  }

  public void setCarrierCompanyCode(String carrierCompanyCode) {
    this.carrierCompanyCode = carrierCompanyCode;
  }

  public DasFees zip(String zip) {
    this.zip = zip;
    return this;
  }

   /**
   * Get zip
   * @return zip
  **/
  @ApiModelProperty(required = true, value = "")
  public String getZip() {
    return zip;
  }

  public void setZip(String zip) {
    this.zip = zip;
  }

  public DasFees dasFeeType(String dasFeeType) {
    this.dasFeeType = dasFeeType;
    return this;
  }

   /**
   * Get dasFeeType
   * @return dasFeeType
  **/
  @ApiModelProperty(required = true, value = "")
  public String getDasFeeType() {
    return dasFeeType;
  }

  public void setDasFeeType(String dasFeeType) {
    this.dasFeeType = dasFeeType;
  }

  public DasFees fee(BigDecimal fee) {
    this.fee = fee;
    return this;
  }

   /**
   * Get fee
   * @return fee
  **/
  @ApiModelProperty(required = true, value = "")
  public BigDecimal getFee() {
    return fee;
  }

  public void setFee(BigDecimal fee) {
    this.fee = fee;
  }

  public DasFees customFields(Map<String, Object> customFields) {
    this.customFields = customFields;
    return this;
  }

  public DasFees putCustomFieldsItem(String key, Object customFieldsItem) {
    if (this.customFields == null) {
      this.customFields = new HashMap<String, Object>();
    }
    this.customFields.put(key, customFieldsItem);
    return this;
  }

   /**
   * Get customFields
   * @return customFields
  **/
  @ApiModelProperty(value = "")
  public Map<String, Object> getCustomFields() {
    return customFields;
  }

  public void setCustomFields(Map<String, Object> customFields) {
    this.customFields = customFields;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DasFees dasFees = (DasFees) o;
    return Objects.equals(this.id, dasFees.id) &&
        Objects.equals(this.createDate, dasFees.createDate) &&
        Objects.equals(this.modifyDate, dasFees.modifyDate) &&
        Objects.equals(this.carrierCompanyCode, dasFees.carrierCompanyCode) &&
        Objects.equals(this.zip, dasFees.zip) &&
        Objects.equals(this.dasFeeType, dasFees.dasFeeType) &&
        Objects.equals(this.fee, dasFees.fee) &&
        Objects.equals(this.customFields, dasFees.customFields);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, createDate, modifyDate, carrierCompanyCode, zip, dasFeeType, fee, customFields);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DasFees {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    createDate: ").append(toIndentedString(createDate)).append("\n");
    sb.append("    modifyDate: ").append(toIndentedString(modifyDate)).append("\n");
    sb.append("    carrierCompanyCode: ").append(toIndentedString(carrierCompanyCode)).append("\n");
    sb.append("    zip: ").append(toIndentedString(zip)).append("\n");
    sb.append("    dasFeeType: ").append(toIndentedString(dasFeeType)).append("\n");
    sb.append("    fee: ").append(toIndentedString(fee)).append("\n");
    sb.append("    customFields: ").append(toIndentedString(customFields)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

